### ISSUE TITLE
failing upgrade to 3_3_0-8

### ISSUE THREAD

**Issue by marcoblancas** [pkp/orcidProfile#190] opened 2021-08-31 12:38 UTC
Upgrading OJS from 3_3_0-7 to 3_3_0-8 I get this error

```
www-data@portatil108:~$ php /home/isaac.marco/git/ojs33/tools/upgrade.php upgrade
PHP Parse error:  syntax error, unexpected 'int' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/isaac.marco/git/ojs33/plugins/generic/orcidProfile/OrcidProfilePlugin.inc.php on line 40

```

plugin is deployed with git.

`git submodule update --init --recursive`

was done.

I'm in tag tag: v1_1_2-21, tag: 3_3_0-8

**Comment by asmecher** [comment] 2021-08-31 14:54
@marcoblancas, yes, there was an accidental change that introduced a PHP7.3 requirement for the ORCID profile plugin. There's already an updated ORCID profile plugin that removes this (see https://github.com/pkp/orcidProfile/pull/189/files), and I'll move the 3_3_0-8 tag shortly to include the fix.

**Comment by asmecher** [comment] 2021-08-31 14:55
(Closing as a duplicate of https://github.com/pkp/orcidProfile/pull/189)

**Closed by asmecher** 2021-08-31 14:54 UTC

**Comment by asmecher** [comment] 2021-09-01 17:20
@marcoblancas, the tag was moved as of yesterday! Please try again and let me know here if you have any trouble.

**Comment by marcoblancas** [comment] 2021-09-01 18:45
But 3_3_0-8 is still pointing to v1_1_2-21 

![imagen](https://user-images.githubusercontent.com/5545390/131724425-341956b6-4266-4aa2-92e2-0e9da357ad9a.png)

I thought it was required to point 3_3_0-8 to v1_1_2-22

**Comment by marcoblancas** [comment] 2021-09-02 16:29
@asmecher , I'm not sure if you received my last comment because I didn't quote you. As you can see in the previous screenshot I see 3_3_0_8 tag pointing to the previous version.

**Comment by asmecher** [comment] 2021-09-02 23:29
@marcoblancas, whoops, I thought you were talking about the tag in the `ojs` repo. I've updated the tag on `orcidProfile` too.

**Comment by marcoblancas** [comment] 2021-09-03 18:43
@asmecher , thank you. Now I was able to upgrade cleanly our site.
